INSERT INTO colors (`hex` , `fa`, `en` ) VALUES
    ('#cd5c5c','جگری','IndianRed'),
    ('#f08080','بژ تیره','LightCoral'),
    ('#fa8072','حناییِ روشن','Salmon'),
    ('#e9967a','قهوه‌ایِ حنایی','DarkSalmon'),
    ('#ffa07a','کرم نارنجی','LightSalmon'),
    ('#ff0000','قرمز','Red'),
    ('#dc143c','زرشکی','Crimson'),
    ('#b22222','شرابی','FireBrick'),
    ('#8b0000','عنابی تند','DarkRed'),
    ('#ffc0cb','صورتی','Pink'),
    ('#ffb6c1','صورتی پررنگ','LightPink'),
    ('#db7093','شرابی روشن','PaleVioletRed'),
    ('#ff69b4','سرخابی','HotPink'),
    ('#ff1493','شفقی','DeepPink'),
    ('#c71585','ارغوانی','MediumVioletRed'),
    ('#ffa07a','نارنجی کرم','LightSalmon'),
    ('#ffa500','نارنجی','Orange'),
    ('#ff8c00','نارنجی سیر','DarkOrange'),
    ('#ff7f50','نارنجی پررنگ','Coral'),
    ('#ff6347','قرمز گوجه‌ای','Tomato'),
    ('#ff4500','قرمز-نارنجی','OrangeRed'),
    ('#ffffe0','شیری','LightYellow'),
    ('#fffacd','شیرشکری','LemonChiffon'),
    ('#fafad2','لیمویی روشن','Light GoldenrodYellow'),
    ('#ffefd5','هلویی روشن','PapayaWhip'),
    ('#ffe4b5','هلویی','Moccasin'),
    ('#ffdab9','هلویی پررنگ','PeachPuff'),
    ('#eee8aa','نخودی','PaleGoldenrod'),
    ('#f0e68c','خاکی','Khaki'),
    ('#ffff00','زرد','Yellow'),
    ('#ffd700','کهربایی باز','Gold'),
    ('#bdb76b','ماشی','DarkKhaki'),
    ('#adff2f','مغزپسته‌ای','GreenYellow'),
    ('#7fff00','سبز روشن','Chartreuse'),
    ('#7cfc00','مغزپسته‌ای پررنگ','LawnGreen'),
    ('#00ff00','مغزپسته‌ای','Lime'),
    ('#98fb98','سبز کمرنگ','PaleGreen'),
    ('#90ee90','سبز کدر','LightGreen'),
    ('#00fa9a','یشمی سیر','MediumSpringGreen'),
    ('#00ff7f','یشمی کمرنگ','SpringGreen'),
    ('#9acd32','سبز لجنی','YellowGreen'),
    ('#32cd32','سبز چمنی','Grassy'),
    ('#3cb371','خزه‌ای','MediumSeaGreen'),
    ('#2e8b57','خزه‌ای پررنگ','SeaGreen'),
    ('#228b22','شویدی','ForestGreen'),
    ('#008000','سبز','Green'),
    ('#6b8e23','سبز ارتشی','OliveDrab'),
    ('#808000','زیتونی','Olive'),
    ('#556b2f','زیتونی سیر','DarkOliveGreen'),
    ('#006400','سبز آووکادو','DarkGreen'),
    ('#66cdaa','سبز دریایی','MediumAquamarine'),
    ('#8fbc8f','سبز دریایی تیره','DarkSeaGreen'),
    ('#20b2aa','سبز کبریتی روشن','LightSeaGreen'),
    ('#008b8b','سبز کبریتی تیره','DarkCyan'),
    ('#008080','سبز دودی','Teal'),
    ('#00ffff','فیروزه‌ای','Aqua'),
    ('#e0ffff','آبی آسمانی','LightCyan'),
    ('#afeeee','فیروزه‌ای کدر','PaleTurquoise'),
    ('#00ffff','آبی دریایی','Cyan'),
    ('#7fffd4','یشمی','Aquamarine'),
    ('#40e0d0','سبز دریایی روشن','Turquoise'),
    ('#48d1cc','فیروزه‌ای تیره','MediumTurquoise'),
    ('#00ced1','فیروزه‌ای سیر','DarkTurquoise'),
    ('#b0e0e6','آبی کبریتی روشن','PowderBlue'),
    ('#b0c4de','بنفش مایل به آبی','LightSteelBlue'),
    ('#add8e6','آبی کبریتی','LightBlue'),
    ('#87ceeb','آبی آسمانی سیر','SkyBlue'),
    ('#87cefa','آبی روشن','LightSkyBlue'),
    ('#00bfff','آبی کمرنگ','DeepSkyBlue'),
    ('#6495ed','آبی کدر','CornflowerBlue'),
    ('#4682b4','نیلی متالیک','SteelBlue'),
    ('#5f9ea0','آبی لجنی','CadetBlue'),
    ('#7b68ee','آبی متالیک روشن','MediumSlateBlue'),
    ('#1e90ff','نیلی','DodgerBlue'),
    ('#4169e1','فیروزه‌ای فسفری','RoyalBlue'),
    ('#0000ff','آبی','Blue'),
    ('#0000cd','آبی سیر','MediumBlue'),
    ('#00008b','سرمه‌ای','DarkBlue'),
    ('#000080','لاجوردی','Navy'),
    ('#191970','آبی نفتی','MidnightBlue'),
    ('#e6e6fa','نیلی کمرنگ','Lavender'),
    ('#d8bfd8','بادمجانی روشن','Thistle'),
    ('#dda0dd','بنفش کدر','Plum'),
    ('#ee82ee','بنفش روشن','Violet'),
    ('#ff00ff','سرخابی','Fuchsia'),
    ('#ff00ff','سرخابی روشن','Magenta'),
    ('#da70d6','ارکیده','Orchid'),
    ('#ba55d3','ارکیده سیر','MediumOrchid'),
    ('#9370db','آبی بنفش','MediumPurple'),
    ('#6a5acd','آبی فولادی','SlateBlue'),
    ('#8a2be2','آبی-بنفش سیر','BlueViolet'),
    ('#9400d3','بنفش باز','DarkViolet'),
    ('#9932cc','ارکیده بنفش','Amethyst'),
    ('#8b008b','مخملی','DarkMagenta'),
    ('#800080','بنفش','Purple'),
    ('#483d8b','آبی دودی','DarkSlateBlue'),
    ('#4b0082','نیلی سیر','Indigo'),
    ('#fff8dc','کاهی','Cornsilk'),
    ('#ffebcd','کاهگلی','BlanchedAlmond'),
    ('#ffe4c4','کرم','Bisque'),
    ('#ffdead','کرم سیر','NavajoWhite'),
    ('#f5deb3','گندمی','Wheat'),
    ('#deb887','خاکی','BurlyWood'),
    ('#d2b48c','برنزه کدر','Tan'),
    ('#bc8f8f','بادمجانی','RosyBrown'),
    ('#f4a460','هلویی سیر','SandyBrown'),
    ('#daa520','خردلی','Goldenrod'),
    ('#b8860b','ماشی سیر','DarkGoldenrod'),
    ('#cd853f','بادامی سیر','Peru'),
    ('#d2691e','عسلی پررنگ','Chocolate'),
    ('#8b4513','کاکائویی','SaddleBrown'),
    ('#a0522d','قهوه‌ای متوسط','Sienna'),
    ('#a52a2a','قهوه‌ای','Brown'),
    ('#800000','آلبالویی','Maroon'),
    ('#ffffff','سفید','White'),
    ('#fffafa','صورتی محو','Snow'),
    ('#f0fff0','یشمی محو','Honeydew'),
    ('#f5fffa','سفید نعنائی','MintCream'),
    ('#f0ffff','آبی محو','Azure'),
    ('#f0f8ff','نیلی محو','AliceBlue'),
    ('#f8f8ff','سفید بنفشه','GhostWhite'),
    ('#f5f5f5','خاکستری محو','WhiteSmoke'),
    ('#fff5ee','بژ باز','Seashell'),
    ('#f5f5dc','هِلی','Beige'),
    ('#fdf5e6','بژ روشن','OldLace'),
    ('#fffaf0','پوست پیازی','FloralWhite'),
    ('#fffff0','استخوانی','Ivory'),
    ('#faebd7','بژ تیره','AntiqueWhite'),
    ('#faf0e6','کتانی','Linen'),
    ('#fff0f5','صورتی مات','LavenderBlush'),
    ('#ffe4e1','بژ','MistyRose'),
    ('#dcdcdc','خاکستری مات','Gainsboro'),
    ('#d3d3d3','نقره‌ای','LightGrey'),
    ('#c0c0c0','توسی','Silver'),
    ('#a9a9a9','خاکستری سیر','DarkGray'),
    ('#808080','خاکستری','Gray'),
    ('#696969','دودی','DimGray'),
    ('#778899','سربی','LightSlateGray'),
    ('#708090','سربی تیره','SlateGray'),
    ('#2f4f4f','لجنی تیره','DarkSlateGray'),
    ('#000000','سیاه','Black');