CREATE TABLE proverbs(
   text VARCHAR(120) NOT NULL PRIMARY KEY
);
INSERT INTO proverbs(text) VALUES ('ادب از که آموختی از بی ادبان');
INSERT INTO proverbs(text) VALUES ('آب در هاون کوبیدن');
INSERT INTO proverbs(text) VALUES ('آش کشک خاله ات رو بخوری پاته نخوری پاته');
INSERT INTO proverbs(text) VALUES ('آش دهانسوزی نیست');
INSERT INTO proverbs(text) VALUES ('آتیش بیار معرکه');
INSERT INTO proverbs(text) VALUES ('آتیش زده به مالش');
INSERT INTO proverbs(text) VALUES ('آب از دستش نمی چکد');
INSERT INTO proverbs(text) VALUES ('آفتاب عمرش لب بومه');
INSERT INTO proverbs(text) VALUES ('آسمون همه جاش یه رنگه');
INSERT INTO proverbs(text) VALUES ('از این ستون به آن ستون فرجی است');
INSERT INTO proverbs(text) VALUES ('آب ازآهن جدا کردن');
INSERT INTO proverbs(text) VALUES ('آب ازدریا بخشیدن');
INSERT INTO proverbs(text) VALUES ('آب برو ، نان برو تو هم به دنبالش برو');
INSERT INTO proverbs(text) VALUES ('اسب تازی گر ضعیف بود همچنان از طویله ی خربه انتقاد از بی اهمیت ها');
INSERT INTO proverbs(text) VALUES ('آن راکه حساب پاک است ا ز محاسبه چه باک است');
INSERT INTO proverbs(text) VALUES ('اندازه نگهدار کلواوشر بواو لا تسرفوا');
INSERT INTO proverbs(text) VALUES ('ای که پنجاه رفت و در خوابی مگر این پنج روز را دریابی');
INSERT INTO proverbs(text) VALUES ('آنروز که آواز بود فکر زمستانت هم بود');
INSERT INTO proverbs(text) VALUES ('آب دریا به دهن سگ نجس نمی شود');
INSERT INTO proverbs(text) VALUES ('بازبان خوش مار را از سوراخ بیرون می کشد');
INSERT INTO proverbs(text) VALUES ('بزک نمیر بهارمیاد .خربزه با خیار می یاد');
INSERT INTO proverbs(text) VALUES ('بادمجان بم آفت نداره');
INSERT INTO proverbs(text) VALUES ('با یک گل بهار نمیشه');
INSERT INTO proverbs(text) VALUES ('با یه من عسل هم نمی شود خوردش');
INSERT INTO proverbs(text) VALUES ('به دعای گربه ی سیاه ، بارون نمی باره');
INSERT INTO proverbs(text) VALUES ('برای لای جزر دیوار خوبه');
INSERT INTO proverbs(text) VALUES ('با یک تیر و دو نشون زدن');
INSERT INTO proverbs(text) VALUES ('باد آورده را باد می برد');
INSERT INTO proverbs(text) VALUES ('به در گفت دیوار بشنوه');
INSERT INTO proverbs(text) VALUES ('به نطق آدمی بهتر است از دواب ، دواب از تو به گر نگویی صواب');
INSERT INTO proverbs(text) VALUES ('با هر دست که دادی پس می گیری. پاداش حتمی در مقابل هر خوبی');
INSERT INTO proverbs(text) VALUES ('بزرگی به عقل است نه به سال.در تقابل بین کارها وسخنان خردمندانه ی خردسال با سخنان وکارهای نابخردانه ی بزرگسال گفته می شود');
INSERT INTO proverbs(text) VALUES ('برای همه مادر است برای من زن بابا');
INSERT INTO proverbs(text) VALUES ('با ماه نشینی ، ماه شوی ، با دیگ نشینی سیاه شوی');
INSERT INTO proverbs(text) VALUES ('با پولها کباب بی پول ها دود کباب');
INSERT INTO proverbs(text) VALUES ('پشت چشم نازک کردن');
INSERT INTO proverbs(text) VALUES ('پشت دست داغ کردن');
INSERT INTO proverbs(text) VALUES ('پا به دریا بگذاره دریا خشک می شود');
INSERT INTO proverbs(text) VALUES ('پرسیدن عیب نیست ،‌ ندانستن عیب است');
INSERT INTO proverbs(text) VALUES ('پنجه با شیر انداختن و مشت با شمشیر زدن کار خردمندان نیست');
INSERT INTO proverbs(text) VALUES ('پول که زیاد شد خانه تنگ می شود و زن زشت');
INSERT INTO proverbs(text) VALUES ('پی تقدیر رفتن از کوری است. در نکوهش سستی وتنبلی ویا استفاده نکردن از عقل وفکر خود');
INSERT INTO proverbs(text) VALUES ('پشم در کلاه نداشتن. بی مایه بودن');
INSERT INTO proverbs(text) VALUES ('پرتو نیکان نگیرد هر که بنیادش بد است تربیت نا اهل را چون گردوگان بر گنبد است');
INSERT INTO proverbs(text) VALUES ('پرده هفت رنگ مگذار تو که در خانه بوریا داری');
INSERT INTO proverbs(text) VALUES ('پولش از پار و بالا می ره');
INSERT INTO proverbs(text) VALUES ('پشت دست را داغ کردن');
INSERT INTO proverbs(text) VALUES ('پایان شب سیه سپید است');
INSERT INTO proverbs(text) VALUES ('پول علف خرس است');
INSERT INTO proverbs(text) VALUES ('پیاده شو با هم راه بریم');
INSERT INTO proverbs(text) VALUES ('توبه گرگ مرگ است');
INSERT INTO proverbs(text) VALUES ('تا تنور گرم است نان را بچسبان');
INSERT INTO proverbs(text) VALUES ('تعارف اومد نیامد دارد');
INSERT INTO proverbs(text) VALUES ('تیرش به سنگ می خوره');
INSERT INTO proverbs(text) VALUES ('تیر توی تاریکی انداختن');
INSERT INTO proverbs(text) VALUES ('تافته جدا بافته بودن');
INSERT INTO proverbs(text) VALUES ('تا توانی دلی بدست آور دل شکستن هنر نمی باشد');
INSERT INTO proverbs(text) VALUES ('تیشه به ریشه زدن');
INSERT INTO proverbs(text) VALUES ('توی هفت آسمون یک ستاره نداشتن');
INSERT INTO proverbs(text) VALUES ('تو را خواهند پرسید که عملت چیست نگویند پدرت کیست');
INSERT INTO proverbs(text) VALUES ('ترسم نرسی به کعبه ای اعرابی که این ره که تو می روی به ترکستان است');
INSERT INTO proverbs(text) VALUES ('تا مردم سخن نگفته باشد عیب و هزش نهفته باشد');
INSERT INTO proverbs(text) VALUES ('توانگری به قناعت به از توانگری به بضاعت');
INSERT INTO proverbs(text) VALUES ('جوجه را آخر پائیز می شمرند');
INSERT INTO proverbs(text) VALUES ('جواب ابلهان خاموشیست');
INSERT INTO proverbs(text) VALUES ('جانماز آب کشیدن');
INSERT INTO proverbs(text) VALUES ('جنگل مولاست');
INSERT INTO proverbs(text) VALUES ('جواب دندان شکن');
INSERT INTO proverbs(text) VALUES ('جایی نمی خوابه که آب زیرش بره');
INSERT INTO proverbs(text) VALUES ('جایی رفت که عرب نی انداخت');
INSERT INTO proverbs(text) VALUES ('جنگ دو سردارد');
INSERT INTO proverbs(text) VALUES ('جاتره بچه نیست');
INSERT INTO proverbs(text) VALUES ('جان کسی را به لب آوردن');
INSERT INTO proverbs(text) VALUES ('جای که نمک خوردی نکمدان مشکن');
INSERT INTO proverbs(text) VALUES ('جهان ای برادر نماند بر کس دل اندر جهان آفرین بند و بس');
INSERT INTO proverbs(text) VALUES ('جای سوزن انداختن نیست');
INSERT INTO proverbs(text) VALUES ('جوانمردی که بخورد و بدهد به از عابری که نخورد و بنهد');
INSERT INTO proverbs(text) VALUES ('جای شکرش باقی است. چرا عاقل کند کاری که باز آرد پشیمانی');
INSERT INTO proverbs(text) VALUES ('چو فردا شد فکر فردا کنیم');
INSERT INTO proverbs(text) VALUES ('چند تا پیراهن بیشتر پاره کرده');
INSERT INTO proverbs(text) VALUES ('چغندر به هرات زیره به کرمون');
INSERT INTO proverbs(text) VALUES ('چیزی که عوض داره گله نداره');
INSERT INTO proverbs(text) VALUES ('چاقو دسته خودش را نمی بره');
INSERT INTO proverbs(text) VALUES ('چیزی بارش نیست');
INSERT INTO proverbs(text) VALUES ('چیزی که از خدا پنهان نیست از بنده چه پنهان');
INSERT INTO proverbs(text) VALUES ('چشم بسته غیب می گوید');
INSERT INTO proverbs(text) VALUES ('چشمش آلبالو گیلاس می چینه');
INSERT INTO proverbs(text) VALUES ('چه خوش گفت آن تهی دست سلحشور جوی زر بهتر از پنجاه من روز');
INSERT INTO proverbs(text) VALUES ('چو آید زپی دشمن جان شان بیند و اجل پای اسب دوان');
INSERT INTO proverbs(text) VALUES ('چوب به لانه زنبور کردن');
INSERT INTO proverbs(text) VALUES ('چو انداختن');
INSERT INTO proverbs(text) VALUES ('چو کردی با کلوخ انداز پیکار سر خود را به نالای شکستی');
INSERT INTO proverbs(text) VALUES ('حساب حسابه ، کاکابرادر');
INSERT INTO proverbs(text) VALUES ('حرف راست را باید از بچه شنید');
INSERT INTO proverbs(text) VALUES ('حسود هرگز نیاسود');
INSERT INTO proverbs(text) VALUES ('حق به حقدار می رسد');
INSERT INTO proverbs(text) VALUES ('حرفهای گنده تر از دهنش می زنه');
INSERT INTO proverbs(text) VALUES ('حالا که ماست نشد شیر بده');
INSERT INTO proverbs(text) VALUES ('حاجی ، حاجی را در مکه می بیند');
INSERT INTO proverbs(text) VALUES ('حسود از نعمت حق بخیل است و بنده بی گناه را دشمن می داند');
INSERT INTO proverbs(text) VALUES ('حال در ماندگان کسی داند که به اصول خویش در ما ند');
INSERT INTO proverbs(text) VALUES ('حادثه خبر نمی کند');
INSERT INTO proverbs(text) VALUES ('حلوا حلوا دهن شیرین نمی شه');
INSERT INTO proverbs(text) VALUES ('حسنی به مکتب نمی رفت وقتی می رفت جمعه می رفت');
INSERT INTO proverbs(text) VALUES ('حرف حساب جواب نداره');
INSERT INTO proverbs(text) VALUES ('حرف حق تلخه');
INSERT INTO proverbs(text) VALUES ('خرما از کرگی هم نداشت');
INSERT INTO proverbs(text) VALUES ('خودم کردم که لعنت بر خودم باد');
INSERT INTO proverbs(text) VALUES ('خانه به دوش');
INSERT INTO proverbs(text) VALUES ('خرتب می کنه');
INSERT INTO proverbs(text) VALUES ('خر بیار و باقالی بار کن');
INSERT INTO proverbs(text) VALUES ('خدا از دهنت بشنوه');
INSERT INTO proverbs(text) VALUES ('خواب زن چپ می زند');
INSERT INTO proverbs(text) VALUES ('خود را به موش مردگی زدن');
INSERT INTO proverbs(text) VALUES ('خوردن برای زیستن و دکر کردن است تو معتقد که زیستن از بهر خوردن است');
INSERT INTO proverbs(text) VALUES ('خران و گاوان کار بردار به ز آدمیان مردم آزار');
INSERT INTO proverbs(text) VALUES ('خر که کمتر نهر بر وی بار بی شک آسوده تر کند رفتار');
INSERT INTO proverbs(text) VALUES ('خواب نوشین بامداد رحیل میل باز دارد سپاه از سبیل عاقبت بد خواب زیاد');
INSERT INTO proverbs(text) VALUES ('خاموشی ، به که جواب سخت');
INSERT INTO proverbs(text) VALUES ('دیگ به دیگ می گه روت سیاه');
INSERT INTO proverbs(text) VALUES ('در نا امیدی بسی امید است پایان شب سیه سپید است');
INSERT INTO proverbs(text) VALUES ('دل به دریا زدن');
INSERT INTO proverbs(text) VALUES ('دل به دل راه داره');
INSERT INTO proverbs(text) VALUES ('در دوازه رو می شه بست ولی در دهان مردم را نمی شود بست');
INSERT INTO proverbs(text) VALUES ('دودو تا چهار تا');
INSERT INTO proverbs(text) VALUES ('دشمن دانا به از دوست نادان');
INSERT INTO proverbs(text) VALUES ('دیوار موش داره موشم گوش داره');
INSERT INTO proverbs(text) VALUES ('در کار نکو حاجت هیچ استخاره نیست');
INSERT INTO proverbs(text) VALUES ('دود از کنده بلند می شه');
INSERT INTO proverbs(text) VALUES ('درخت هرچه بارش بیشتر می شود سر فروتر می رود. در ستایش فروتنی افراد دارای مقام ویا ثروت');
INSERT INTO proverbs(text) VALUES ('دروغی مصلحت آمیز به که داشتی فتنه انگیز');
INSERT INTO proverbs(text) VALUES ('دوست شمار آنکه در نعمت زند لاف یاری و برادر خواندگی');
INSERT INTO proverbs(text) VALUES ('دشمن آن به که نیکی بینند');
INSERT INTO proverbs(text) VALUES ('داشتم فایده نداره از داریم بگو');
INSERT INTO proverbs(text) VALUES ('روکه نیست سنگ پای قزوینه');
INSERT INTO proverbs(text) VALUES ('رفتم ثواب کنم کباب شدم');
INSERT INTO proverbs(text) VALUES ('راه باز است و جاده دراز');
INSERT INTO proverbs(text) VALUES ('روده بزرگه ، روده کوچکه رو خورد');
INSERT INTO proverbs(text) VALUES ('رنگش مثل گچ سفید شد');
INSERT INTO proverbs(text) VALUES ('رفتن و نشستن به که دویدن و گسستن');
INSERT INTO proverbs(text) VALUES ('روده تنگ به یک نان تهی پر گردد نعمت روی زمین پر نکند و بهره ننگ');
INSERT INTO proverbs(text) VALUES ('رگ خواب کسی را به دست آورن. پیدا کردن نقطه ی ضعف کسی');
INSERT INTO proverbs(text) VALUES ('ریش در دست دیگران داشتن. اختیار در دست خود نداشتن');
INSERT INTO proverbs(text) VALUES ('رفت که ریش در بیاورد ، سبیلش را هم باخت');
INSERT INTO proverbs(text) VALUES ('ز تعارف کم کن و بر مبلغ افزا');
INSERT INTO proverbs(text) VALUES ('زدیم و نگرفت');
INSERT INTO proverbs(text) VALUES ('زبانم مو در آورد');
INSERT INTO proverbs(text) VALUES ('زیر آب کسی را زدن');
INSERT INTO proverbs(text) VALUES ('زیر کاسه ، نیم کاسه است');
INSERT INTO proverbs(text) VALUES ('زردآلو را می خورد برای هسته اش');
INSERT INTO proverbs(text) VALUES ('زن به در سرای مرد نکو هم درین عالم است دوزخ او تأثیرخوب همنیشنی با افراد نیکوکار');
INSERT INTO proverbs(text) VALUES ('زیر رنج بود گنج های پنهانی');
INSERT INTO proverbs(text) VALUES ('سری که درد نمی کند دستمال نمی بندند');
INSERT INTO proverbs(text) VALUES ('سیب دو نیمه');
INSERT INTO proverbs(text) VALUES ('سرش به تنش زیادی کرده است');
INSERT INTO proverbs(text) VALUES ('سکوت نشانه ی رضایت است');
INSERT INTO proverbs(text) VALUES ('سرش به تنش می ارزد');
INSERT INTO proverbs(text) VALUES ('سگ زرد برادر شغال است');
INSERT INTO proverbs(text) VALUES ('سبیلش را چرب کردن');
INSERT INTO proverbs(text) VALUES ('سر پیری و معرکه گیری');
INSERT INTO proverbs(text) VALUES ('سالی که نکوست از بهارش پیداست');
INSERT INTO proverbs(text) VALUES ('سیر به پیاز میگه پیف پیف چقدر بو می دی');
INSERT INTO proverbs(text) VALUES ('سه چیز پایداری نماند مال بی تجارت و علم بی بحث و ملک بی سیاست');
INSERT INTO proverbs(text) VALUES ('سخن را سر است ای خردمند و بن میاور سخن در میان سخن');
INSERT INTO proverbs(text) VALUES ('سخنران پرورده ی پیرکهن بیندیشد آنکه بگوید سخن');
INSERT INTO proverbs(text) VALUES ('سخی دوست خداست ‌');
INSERT INTO proverbs(text) VALUES ('ستاره ی سهیل است شتر در خواب بیند پنبه دانه ؟');
INSERT INTO proverbs(text) VALUES ('شنیدن کی بود مانند دیدن');
INSERT INTO proverbs(text) VALUES ('شتر بابارش گم می شه');
INSERT INTO proverbs(text) VALUES ('شتر سواری دولا دولا نمی شود');
INSERT INTO proverbs(text) VALUES ('شاهنامه آخرش خوش است');
INSERT INTO proverbs(text) VALUES ('شتری که در خانه ی همه را می زند');
INSERT INTO proverbs(text) VALUES ('شمر ، جلودارش نمیشه');
INSERT INTO proverbs(text) VALUES ('شنیدم گوسفند را بزرگی رها نیندازدهان و دست گرگی');
INSERT INTO proverbs(text) VALUES ('شیطان با مخلصان بر نمی آید و سلطان با مفلسان');
INSERT INTO proverbs(text) VALUES ('شوی زن زشت روی و نابینا به');
INSERT INTO proverbs(text) VALUES ('شام و ناهار هیچ چیز ،‌آفتاب به لگن هفت دست');
INSERT INTO proverbs(text) VALUES ('صد تا چاقو بسازه ، یکیش دسته نداره');
INSERT INTO proverbs(text) VALUES ('صورتش را با سیلی سرخ نگاه می دارد');
INSERT INTO proverbs(text) VALUES ('صبر ،‌کلید کارهاست');
INSERT INTO proverbs(text) VALUES ('صیاد بی روزی در دجله نگیرد و ماهی بی اجل بر خشک نمیرد');
INSERT INTO proverbs(text) VALUES ('صبر ایوب داشتن');
INSERT INTO proverbs(text) VALUES ('صلاح مملکت خویش خسروان دانند');
INSERT INTO proverbs(text) VALUES ('صاحب دلی به مدرسه آمد ز خانقاه شکست عهد صحبت اهل طریق را');
INSERT INTO proverbs(text) VALUES ('صدا از ته چاه بر آمدن. ضعیف بودن');
INSERT INTO proverbs(text) VALUES ('صلح دشمن چو جنگ دوست بود');
INSERT INTO proverbs(text) VALUES ('ضرر تلخه');
INSERT INTO proverbs(text) VALUES ('ضرب ، ضرب اول');
INSERT INTO proverbs(text) VALUES ('ضامن روزی بود روزی رسان. اعتقاد به روزی دهندگی خدا');
INSERT INTO proverbs(text) VALUES ('ضعیفی که با قوی دلاور کند یار دشمن است در هلاک خویش');
INSERT INTO proverbs(text) VALUES ('طوطی وار یاد گرفتن');
INSERT INTO proverbs(text) VALUES ('طبل توخالیست');
INSERT INTO proverbs(text) VALUES ('طاووس‌ را به‌ نقش و نگاری‌ که هست‌ خلق‌ تحسین‌ کنند و او خجل از پای‌ زشت‌ خویش');
INSERT INTO proverbs(text) VALUES ('طلب کردم زدانایی به یک پند مرا فرمود با نادان مپیوند');
INSERT INTO proverbs(text) VALUES ('طمع را سه حرف است هر سه تهی');
INSERT INTO proverbs(text) VALUES ('عقل اون پاره سنگ بر می داره');
INSERT INTO proverbs(text) VALUES ('عجله کار شیطونه');
INSERT INTO proverbs(text) VALUES ('عاقبت حق به حقدار رسید');
INSERT INTO proverbs(text) VALUES ('عالم نا پرهیزگار کور شعله دارست');
INSERT INTO proverbs(text) VALUES ('عالم از بهر دین پروردن است نه از بهر دنیا خوردن');
INSERT INTO proverbs(text) VALUES ('عالم بی عمل به چه ماند گفت به زنبور بی عسل');
INSERT INTO proverbs(text) VALUES ('عاقلان را یک اشارت بس بود');
INSERT INTO proverbs(text) VALUES ('عروس تعریفی آخرش شلخته در می آید. دوری از تکبر ویا خودتعریفی');
INSERT INTO proverbs(text) VALUES ('عطای او را بلقای او بخشیدم');
INSERT INTO proverbs(text) VALUES ('فیلش یاد هندوستان کرده');
INSERT INTO proverbs(text) VALUES ('فلفل نبین چه ریزه بشکن ببین چه تیزه');
INSERT INTO proverbs(text) VALUES ('فردا هم روز خداست');
INSERT INTO proverbs(text) VALUES ('فلانی اجاقش کوره');
INSERT INTO proverbs(text) VALUES ('فرو مایه هزار سنگ بر می دارد و طاقت سختی نمی آورد. بی تحمل و طاقتبودن افراد بدکار');
INSERT INTO proverbs(text) VALUES ('فرق است میان آنکه یارش در بر آنکه دو چشم انتظارش بر در');
INSERT INTO proverbs(text) VALUES ('فهم سخن چون نکند مستمع قوت طبع از متلکم بجوی');
INSERT INTO proverbs(text) VALUES ('فکر نان کن که خربزه آب است');
INSERT INTO proverbs(text) VALUES ('قصاص در این دنیاست');
INSERT INTO proverbs(text) VALUES ('قاشق نداره آش بخورد');
INSERT INTO proverbs(text) VALUES ('قوز بالاقوز');
INSERT INTO proverbs(text) VALUES ('قرص خورشید در سیاهی شد یونس اندر دهان ماهی شد');
INSERT INTO proverbs(text) VALUES ('قرآن بر سر زبان است و در میان جان');
INSERT INTO proverbs(text) VALUES ('قدر عافیت کسی داند که به مصیبتی گرفتار آید');
INSERT INTO proverbs(text) VALUES ('کبکش خروس می خونه');
INSERT INTO proverbs(text) VALUES ('کوگوش شنوا');
INSERT INTO proverbs(text) VALUES ('کوزه گر از کوزه شکسته آب می خورد');
INSERT INTO proverbs(text) VALUES ('کارها به صبر برآید و مستعجل به سر در آید');
INSERT INTO proverbs(text) VALUES ('کس نبیند بخیل فاضل را کر نه در عیب گفتنش کوشد ور کریمی دو صد گز دارد کرمش عیبها فرو پوشد');
INSERT INTO proverbs(text) VALUES ('کرم بین و لطف خداوند گار گر بنده کرده است و او شرمسار');
INSERT INTO proverbs(text) VALUES ('کند همجنس با همنجنس پرواز');
INSERT INTO proverbs(text) VALUES ('گاومون زائیده');
INSERT INTO proverbs(text) VALUES ('گاو پیشانی سفید است');
INSERT INTO proverbs(text) VALUES ('گاو بی شاخ و دم');
INSERT INTO proverbs(text) VALUES ('گر دست فتاده ای بگیری مردی ور بر کسی خرده نگیری مردی');
INSERT INTO proverbs(text) VALUES ('گربه شیر است در گرفتن موش لیک موش است در مصاف پلنگ');
INSERT INTO proverbs(text) VALUES ('گرت از دست برآید ذهنی شیرین کف مردی آن نیست که مشتی بزنی بر دهنی');
INSERT INTO proverbs(text) VALUES ('گرگ که پیر می شود ، رقاص شغال می شود');
INSERT INTO proverbs(text) VALUES ('لگد به بخت خود زدن');
INSERT INTO proverbs(text) VALUES ('نقش دادن');
INSERT INTO proverbs(text) VALUES ('لبش بوی شیر می دهد');
INSERT INTO proverbs(text) VALUES ('همه مهربانتر از مادر');
INSERT INTO proverbs(text) VALUES ('لذتی که در بخشش هست در انتقام نیست وقتی می توان ببخشی انتقام نگیر');
INSERT INTO proverbs(text) VALUES ('مرغ همسایه غاز است');
INSERT INTO proverbs(text) VALUES ('ماهی را هر وقت از آب بگیری تازه است');
INSERT INTO proverbs(text) VALUES ('ماست را کیسه کردن');
INSERT INTO proverbs(text) VALUES ('مرغ یک پا داره');
INSERT INTO proverbs(text) VALUES ('مار تو آستین پرورش دادن');
INSERT INTO proverbs(text) VALUES ('مار خورده و افعی شده');
INSERT INTO proverbs(text) VALUES ('مگواندوه خویش با دشمنان که لامول گویند شادی کنان');
INSERT INTO proverbs(text) VALUES ('مال از بهر آسایش عمر است نه عمر از بهر گرد کردن مال');
INSERT INTO proverbs(text) VALUES ('مورچگان را چو بود اتفاق شیر ژیان را به راننده پوست');
INSERT INTO proverbs(text) VALUES ('مزن بی تأمل بگفتار دم نگو گوی گردوگوئی چه غم');
INSERT INTO proverbs(text) VALUES ('مار گزیده از ریسمان سیاه و سفید می ترسد');
INSERT INTO proverbs(text) VALUES ('مسکین خر اگر چه تمیز است چون با رهمی برد عزیز است');
INSERT INTO proverbs(text) VALUES ('نفس از جای گرم برآمدن');
INSERT INTO proverbs(text) VALUES ('نم پس نمی دهد');
INSERT INTO proverbs(text) VALUES ('نخود هر آش شدن');
INSERT INTO proverbs(text) VALUES ('نور علا نور بودن');
INSERT INTO proverbs(text) VALUES ('نان خود خوردن و نشستن به که کمر زرین بستن و به خدمت ایستادن');
INSERT INTO proverbs(text) VALUES ('نصیحت پادشاهان کردن کسی رامسلم بود که نیم سرندارد یاامید. کاربیهوده');
INSERT INTO proverbs(text) VALUES ('ندانستی که بینی بر پای چو در گوشت نیامد مردم');
INSERT INTO proverbs(text) VALUES ('نماند به ستمکار بد، روزگار بماند بر او لعنت پایدار');
INSERT INTO proverbs(text) VALUES ('نان از برای کنج عبادت گرفته اند صاحب دلان به کنج عبادت برای نان');
INSERT INTO proverbs(text) VALUES ('نا بینا به کار خویش بیناست');
INSERT INTO proverbs(text) VALUES ('وجود یکی است ولی شکم دوتاست');
INSERT INTO proverbs(text) VALUES ('وقت نداره سرشو بخارونه');
INSERT INTO proverbs(text) VALUES ('وین شکم بی هنر پیچ ، پیچ صبر ندارد که بسازد به هیچ');
INSERT INTO proverbs(text) VALUES ('وقت ضرورت چون نماند گزیر دست‌بگیردسرشمشیرتیز');
INSERT INTO proverbs(text) VALUES ('وفاداری مدار از بلبلان چشم که هردم بر گلی دیگر سرآیند');
INSERT INTO proverbs(text) VALUES ('هر پستی ، بلندی دارد');
INSERT INTO proverbs(text) VALUES ('هادی ، هادی اسم خود بر ما نهادی');
INSERT INTO proverbs(text) VALUES ('هشتش گرو نهش است');
INSERT INTO proverbs(text) VALUES ('هر که بامش بیش ، برفش بیشتر');
INSERT INTO proverbs(text) VALUES ('هرکه درحال‌توانایی نکوئی‌نکند ازوقت ناتوانی‌سختی ببیند');
INSERT INTO proverbs(text) VALUES ('هرکه در زندگانی نانش بخورند چون بمیرد نامش نبرند');
INSERT INTO proverbs(text) VALUES ('هر که آمد عمارتی نو ساخت رفت و منزل بدیگری پرداخت');
INSERT INTO proverbs(text) VALUES ('هر که نان از عمل خویش خورد منت از حاتم طائی نبرد');
INSERT INTO proverbs(text) VALUES ('هر که با بزرگان ستیز و خون خود ریزد');
INSERT INTO proverbs(text) VALUES ('هر جا سر است سخن است');
INSERT INTO proverbs(text) VALUES ('یکی به دو کردن');
INSERT INTO proverbs(text) VALUES ('یک دست صدا نداره');
INSERT INTO proverbs(text) VALUES ('یک من ماست چقدر کره می دهد');
INSERT INTO proverbs(text) VALUES ('یک پاش لب گور است');
INSERT INTO proverbs(text) VALUES ('یزدان کسی را که دارد نگاه نگردد ز سرما و گرما تباه');
INSERT INTO proverbs(text) VALUES ('یاردیرینه‌مراگونه‌زبان توبه مده که مراتوبه‌شمشیری نخواهدبودن');
INSERT INTO proverbs(text) VALUES ('یک تیر و دو نشان');
INSERT INTO proverbs(text) VALUES ('یاسین به گوش خر خواندن');
INSERT INTO proverbs(text) VALUES ('یک چشم گریان و یک خندان');
INSERT INTO proverbs(text) VALUES ('بگیر و ببند بده دست پهلوون !');
INSERT INTO proverbs(text) VALUES ('بلبل هفت تا بچه میزاره، شیش تاش سسکه، یکیش بلبل !');
INSERT INTO proverbs(text) VALUES ('بمالت نناز که بیک شب بنده، به حسنت نناز که بیک تب بنده !');
INSERT INTO proverbs(text) VALUES ('بماه میگه تو در نیا من در میام !');
INSERT INTO proverbs(text) VALUES ('بمرغشان کیش نمیشه گفت !');
INSERT INTO proverbs(text) VALUES ('بمرگ میگیره تا به تب راضی بشه !');
INSERT INTO proverbs(text) VALUES ('بوجار لنجونه از هر طرف باد بیاد، بادش میده !');
INSERT INTO proverbs(text) VALUES ('بهر کجا که روی آسمان همین رنگه !');
INSERT INTO proverbs(text) VALUES ('به یکی گفتند');
INSERT INTO proverbs(text) VALUES ('بمیر و بدم !');
INSERT INTO proverbs(text) VALUES ('به گاو و گوسفند کسی کاری نداره !');
INSERT INTO proverbs(text) VALUES ('بیله دیگ، بیله چغندر !');
INSERT INTO proverbs(text) VALUES ('« پ » پا را به اندازه گلیم باید دراز کرد !');
INSERT INTO proverbs(text) VALUES ('پای خروستو ببند، بمرغ همسایه هیز نگو !');
INSERT INTO proverbs(text) VALUES ('پایین پایین ها جاش نیست، بالا بالا ها راش نیست !');
INSERT INTO proverbs(text) VALUES ('پز عالی، جیب خالی !');
INSERT INTO proverbs(text) VALUES ('پس از چهل سال چارواداری، الاغ خودشو نمیشناسه !');
INSERT INTO proverbs(text) VALUES ('پس از قرنی شنبه به نوروز میافته !');
INSERT INTO proverbs(text) VALUES ('پستان مادرش را گاز گرفته !');
INSERT INTO proverbs(text) VALUES ('پسر خاله دسته دیزی !');
INSERT INTO proverbs(text) VALUES ('پسر زائیدم برای رندان، دختر زائیدم برای مردان، موندم سفیل و سرگردان !');
INSERT INTO proverbs(text) VALUES ('پدر کو ندارد نشان از پدر — تو بیگانه خوانش نخوانش پسر !');
INSERT INTO proverbs(text) VALUES ('پشت تاپو بزرگ شده !');
INSERT INTO proverbs(text) VALUES ('پنج انگشت برادرند، برابر نیستند !');
INSERT INTO proverbs(text) VALUES ('پوست خرس نزده میفروشه !');
INSERT INTO proverbs(text) VALUES ('پول است نه جان است که آسان بتوان داد !');
INSERT INTO proverbs(text) VALUES ('پول پیدا کردن آسونه، اما نگهداریش مشکله !');
INSERT INTO proverbs(text) VALUES ('پول حرام، یا خرج شراب شور میشه یا شاهد کور !');
INSERT INTO proverbs(text) VALUES ('پولدارها به کباب، بی پولها به بوی کباب !');
INSERT INTO proverbs(text) VALUES ('از نو کیسه قرض مکن، قرض کردی خرج نکن !');
INSERT INTO proverbs(text) VALUES ('از هر چه بدم اومد، سرم اومد !');
INSERT INTO proverbs(text) VALUES ('از هول هلیم افتاد توی دیگ !');
INSERT INTO proverbs(text) VALUES ('از یک گل بهار نمیشه !');
INSERT INTO proverbs(text) VALUES ('از این گوش میگیره، از آن گوش در میکنه !');
INSERT INTO proverbs(text) VALUES ('اسباب خونه به صاحبخونه میره !');
INSERT INTO proverbs(text) VALUES ('اسب پیشکشی رو، دندوناشو نمیشمرند !');
INSERT INTO proverbs(text) VALUES ('اسب ترکمنی است، هم از توبره میخوره هم ازآخور !');
INSERT INTO proverbs(text) VALUES ('اسب دونده جو خود را زیاد میکنه !');
INSERT INTO proverbs(text) VALUES ('اسب را گم کرده، پی نعلش میگرده !');
INSERT INTO proverbs(text) VALUES ('اسب و خر را که یکجا ببندند، اگر همبو نشند همخو میشند !');
INSERT INTO proverbs(text) VALUES ('استخری که آب نداره، اینهمه قورباغه میخواد چکار ؟!');
INSERT INTO proverbs(text) VALUES ('اصل کار برو روست، کچلی زیر موست !');
INSERT INTO proverbs(text) VALUES ('اکبر ندهد، خدای اکبر بدهد !');
INSERT INTO proverbs(text) VALUES ('اگر بیل زنی، باغچه خودت را بیل بزن !');
INSERT INTO proverbs(text) VALUES ('اگر برای من آب نداره، برای تو که نان داره !');
INSERT INTO proverbs(text) VALUES ('اگر بپوشی رختی، بنشینی به تختی، تازه می بینمت بچشم آن وختی !');
INSERT INTO proverbs(text) VALUES ('اگه باباشو ندیده بود، ادعای پادشاهی میکرد !');
INSERT INTO proverbs(text) VALUES ('اگه پشیمونی شاخ بود، فلانی شاخش بآسمان میرسید !');
INSERT INTO proverbs(text) VALUES ('اگه تو مرا عاق کنی، منهم ترا عوق میکنم !');
INSERT INTO proverbs(text) VALUES ('اگر جراحی، پیزی خود تو جا بنداز !');
INSERT INTO proverbs(text) VALUES ('اگه خدا بخواهد، از نر هم میدهد !');
INSERT INTO proverbs(text) VALUES ('اگه خاله ام ریش داشت، آقا دائیم بود !');
INSERT INTO proverbs(text) VALUES ('اگه خیر داشت، اسمشو می گذاشتند خیرالله !');
INSERT INTO proverbs(text) VALUES ('اگر دانی که نان دادن ثواب است — تو خود میخور که بغدادت خرابست !');
INSERT INTO proverbs(text) VALUES ('اگه دعای بچه ها اثر داشت، یک معلم زنده نمی موند !');
INSERT INTO proverbs(text) VALUES ('اگه زاغی کنی، روقی کنی، میخورمت !');
INSERT INTO proverbs(text) VALUES ('اگه زری بپوشی، اگر اطلس بپوشی، همون کنگر فروشی !');
INSERT INTO proverbs(text) VALUES ('اگه علی ساربونه، میدونه شترو کجا بخوابونه !');
INSERT INTO proverbs(text) VALUES ('اگه کلاغ جراح بود، ماتحت خودشو بخیه میزد');
INSERT INTO proverbs(text) VALUES ('اگه لالائی بلدی، چرا خوابت نمیبره !');
INSERT INTO proverbs(text) VALUES ('اگه لر ببازار نره بازار میگنده !');
INSERT INTO proverbs(text) VALUES ('اگه مردی، سر این دسته هونگ ( هاون ) و بشکن !');
INSERT INTO proverbs(text) VALUES ('اگه بگه ماست سفیده، من میگم سیاهه !');
INSERT INTO proverbs(text) VALUES ('اگه مهمون یکی باشه، صاحبخونه براش گاو می کشه !');
INSERT INTO proverbs(text) VALUES ('اگه نخوردیم نون گندم، دیدیم دست مردم !');
INSERT INTO proverbs(text) VALUES ('اگه نی زنی چرا بابات از حصبه مرد !');
INSERT INTO proverbs(text) VALUES ('اگه هفت تا دختر کور داشته باشه، یکساعته شوهر میده !');
INSERT INTO proverbs(text) VALUES ('اگه همه گفتند نون و پنیر، تو سرت را بگذار زمین و بمیر !');
INSERT INTO proverbs(text) VALUES ('امان از خانه داری، یکی میخری دو تا نداری !');
INSERT INTO proverbs(text) VALUES ('امان ازدوغ لیلی ، ماستش کم بود آبش خیلی !');
INSERT INTO proverbs(text) VALUES ('انگور خوب، نصیب شغال میشه !');
INSERT INTO proverbs(text) VALUES ('اوسا علم ! این یکی رو بکش قلم !');
INSERT INTO proverbs(text) VALUES ('اولاد، بادام است اولاد اولاد، مغز بادام !');
INSERT INTO proverbs(text) VALUES ('اول بچش، بعد بگو بی نمکه !');
INSERT INTO proverbs(text) VALUES ('اول برادریتو ثابت کن، بعد ادعای ارث و میراث کن !');
INSERT INTO proverbs(text) VALUES ('اول بقالی و ماست ترش فروشی !');
INSERT INTO proverbs(text) VALUES ('اول پیاله و بد مستی !');
INSERT INTO proverbs(text) VALUES ('اول ، چاه را بکن، بعد منار را بدزد !');
INSERT INTO proverbs(text) VALUES ('ای آقای کمر باریک، کوچه روشن کن و خانه تاریک !');
INSERT INTO proverbs(text) VALUES ('این تو بمیری، از آن تو بمیری ها نیست !');
INSERT INTO proverbs(text) VALUES ('اینجا کاشون نیست که کپه با فعله باشه !');
INSERT INTO proverbs(text) VALUES ('این حرفها برای فاطی تنبون نمیشه !');
INSERT INTO proverbs(text) VALUES ('این قافله تا به حشر لنگه !');
INSERT INTO proverbs(text) VALUES ('اینکه برای من آوردی، ببر برای خاله ات !');
INSERT INTO proverbs(text) VALUES ('اینو که زائیدی بزرگ کن !');
INSERT INTO proverbs(text) VALUES ('این هفت صنار غیر از اون چارده شی است !');
INSERT INTO proverbs(text) VALUES ('اینهمه چریدی دنبه ات کو ؟!');
INSERT INTO proverbs(text) VALUES ('اینهمه خر هست و ما پیاده میریم !');
INSERT INTO proverbs(text) VALUES ('« ب » با آل علی هر که در افتاد ، ور افتاد');
INSERT INTO proverbs(text) VALUES ('با اون زبون خوشت، با پول زیادت، یا با راه نزدیکت !');
INSERT INTO proverbs(text) VALUES ('با این ریش میخواهی بری تجریش ؟');
INSERT INTO proverbs(text) VALUES ('با پا راه بری کفش پاره میشه، با سر کلاه !');
INSERT INTO proverbs(text) VALUES ('با خوردن سیرشدی با لیسیدن نمیشی !');
INSERT INTO proverbs(text) VALUES ('باد آورده را باد میبرد !');
INSERT INTO proverbs(text) VALUES ('با دست پس میزنه، با پا پیش میکشه !');
INSERT INTO proverbs(text) VALUES ('بادنجان بم آفت ندارد !');
INSERT INTO proverbs(text) VALUES ('بارون آمد، ترکها بهم رفت !');
INSERT INTO proverbs(text) VALUES ('بار کج به منزل نمیرسد !');
INSERT INTO proverbs(text) VALUES ('با رمال شاعر است، با شاعر رمال، با هر دو هیچکدام با هرهیچکدام هر دو !');
INSERT INTO proverbs(text) VALUES ('بازی اشکنک داره ، سر شکستنک داره !');
INSERT INTO proverbs(text) VALUES ('بازی بازی، با ریش بابا هم بازی !');
INSERT INTO proverbs(text) VALUES ('با سیلی صورت خودشو سرخ نگهمیداره !');
INSERT INTO proverbs(text) VALUES ('با کدخدا بساز، ده را بچاپ !');
INSERT INTO proverbs(text) VALUES ('با گرگ دنبه میخوره، با چوپان گریه میکنه !');
INSERT INTO proverbs(text) VALUES ('بالابالاها جاش نیست، پائین پائین ها راش نیست !');
INSERT INTO proverbs(text) VALUES ('بالاتو دیدیم ، پائینتم دیدیم !');
INSERT INTO proverbs(text) VALUES ('با مردم زمانه سلامی و والسلام');
INSERT INTO proverbs(text) VALUES ('تا گفته ای غلام توام، میفروشنت !');
INSERT INTO proverbs(text) VALUES ('با نردبان به آسمون نمیشه رفت !');
INSERT INTO proverbs(text) VALUES ('با همین پرو پاچین، میخواهی بری چین و ماچین ؟');
INSERT INTO proverbs(text) VALUES ('باید گذاشت در کوزه آبش را خورد !');
INSERT INTO proverbs(text) VALUES ('با یکدست دو هندوانه نمیشود برداشت !');
INSERT INTO proverbs(text) VALUES ('با یک گل بهار نمیشه !');
INSERT INTO proverbs(text) VALUES ('به اشتهای مردم نمیشود نان خورد !');
INSERT INTO proverbs(text) VALUES ('به بهلول گفتند ریش تو بهتره یا دم سگ ؟ گفت اگر از پل جستم رریش من و گرنه دم سگ !');
INSERT INTO proverbs(text) VALUES ('بجای شمع کافوری چراغ نفت میسوزد !');
INSERT INTO proverbs(text) VALUES ('بچه سر پیری زنگوله پای تابوته !');
INSERT INTO proverbs(text) VALUES ('بچه سر راهی برداشتم پسرم بشه، شوهرم شد !');
INSERT INTO proverbs(text) VALUES ('بخور و بخواب کار منه، خدا نگهدار منه !');
INSERT INTO proverbs(text) VALUES ('بد بخت اگر مسجد آدینه بسازد — یا طاق فرود آید، یا قبله کج آید !');
INSERT INTO proverbs(text) VALUES ('به درویشه گفتند بساطتو جمع کن ، دستشو گذاشت در دهنش !');
INSERT INTO proverbs(text) VALUES ('بدعای گربه کوره بارون نمیاد !');
INSERT INTO proverbs(text) VALUES ('بدهکار رو که رو بدی طلبکار میشه !');
INSERT INTO proverbs(text) VALUES ('برادران جنگ کنند، ابلهان باورکنند !');
INSERT INTO proverbs(text) VALUES ('برادر پشت ، برادر زاده هم پشت');
INSERT INTO proverbs(text) VALUES ('خواهر زاده را با زر بخر با سنگ بکش!');
INSERT INTO proverbs(text) VALUES ('برادری بجا، بزغاله یکی هفت صنار !');
INSERT INTO proverbs(text) VALUES ('برای کسی بمیر که برات تب کنه !');
INSERT INTO proverbs(text) VALUES ('برای همه مادره، برای ما زن بابا !');
INSERT INTO proverbs(text) VALUES ('برای یک بی نماز، در مسجد و نمی بندند !');
INSERT INTO proverbs(text) VALUES ('برای یه دستمال قیصریه رو آتیش میزنه !');
INSERT INTO proverbs(text) VALUES ('بر عکس نهند نام زنگی کافور !');
INSERT INTO proverbs(text) VALUES ('به روباهه گفتند شاهدت کیه ؟ گفت');
INSERT INTO proverbs(text) VALUES ('بزبون خوش مار از سوراخ در میاد !');
INSERT INTO proverbs(text) VALUES ('بزک نمیر بهار میاد — کنبزه با خیار میاد !');
INSERT INTO proverbs(text) VALUES ('بز گر از سر چشمه آب میخوره !');
INSERT INTO proverbs(text) VALUES ('به شتره گفتند شاشت از پسه ، گفت');
INSERT INTO proverbs(text) VALUES ('به شتر مرغ گفتند بار ببر، گفت');
INSERT INTO proverbs(text) VALUES ('بعد از چهل سال گدایی، شب جمعه را گم کرده !');
INSERT INTO proverbs(text) VALUES ('بعد از هفت کره، ادعای بکارت !');
INSERT INTO proverbs(text) VALUES ('بقاطر گفتند بابات کیه ؟ گفت');
INSERT INTO proverbs(text) VALUES ('به کیشی آمدند به فیشی رفتند !');
INSERT INTO proverbs(text) VALUES ('به گربه گفتند گهت درمونه، خاک پاشید روش !');
INSERT INTO proverbs(text) VALUES ('به کچله گفتند');
INSERT INTO proverbs(text) VALUES ('به کک بنده که رقاص خداست !');
INSERT INTO proverbs(text) VALUES ('بگو نبین، چشممو هم میگذارم، بگو نشنو در گوشمو میگیرم، اما اگر بگی نفهمم، نمیتونم !');
INSERT INTO proverbs(text) VALUES ('از خودت گذشته، خدا عقلی به بچه هات بده !');
INSERT INTO proverbs(text) VALUES ('از درد لا علاجی به خر میگه خانمباجی !');
INSERT INTO proverbs(text) VALUES ('از دور دل و میبره، از جلو زهره رو !');
INSERT INTO proverbs(text) VALUES ('از سه چیز باید حذر کرد، دیوار شکسته، سگ درنده، زن سلیطه !');
INSERT INTO proverbs(text) VALUES ('از شما عباسی، از ما رقاصی !');
INSERT INTO proverbs(text) VALUES ('از کوزه همان برون تراود که در اوست ! (( گر دایره کوزه ز گوهر سازند ))');
INSERT INTO proverbs(text) VALUES ('از کیسه خلیفه می بخشه !');
INSERT INTO proverbs(text) VALUES ('از گدا چه یک نان بگیرند و چه بدهند !');
INSERT INTO proverbs(text) VALUES ('از گیر دزد در آمده، گیر رمال افتاد !');
INSERT INTO proverbs(text) VALUES ('از ماست که بر ماست !');
INSERT INTO proverbs(text) VALUES ('از مال پس است و از جان عاصی !');
INSERT INTO proverbs(text) VALUES ('از مردی تا نامردی یک قدم است !');
INSERT INTO proverbs(text) VALUES ('از من بدر، به جوال کاه !');
INSERT INTO proverbs(text) VALUES ('از نخورده بگیر، بده به خورده !');
INSERT INTO proverbs(text) VALUES ('الف » آب از دستش نمیچکه !');
INSERT INTO proverbs(text) VALUES ('آب از سر چشمه گله !');
INSERT INTO proverbs(text) VALUES ('آب از آب تکان نمیخوره !');
INSERT INTO proverbs(text) VALUES ('آب از سرش گذشته !');
INSERT INTO proverbs(text) VALUES ('آب پاکی روی دستش ریخت !');
INSERT INTO proverbs(text) VALUES ('آب در کوزه و ما تشنه لبان میگردیم !');
INSERT INTO proverbs(text) VALUES ('آب را گل آلود میکنه که ماهی بگیره !');
INSERT INTO proverbs(text) VALUES ('آب زیر پوستش افتاده !');
INSERT INTO proverbs(text) VALUES ('آب که یه جا بمونه، میگنده');
INSERT INTO proverbs(text) VALUES ('آبکش و نگاه کن که به کفگیر میگه تو سه سوراخ داری !');
INSERT INTO proverbs(text) VALUES ('آب که از سر گذشت، چه یک ذرع چه صد ذرع ـ چه یک نی چه چه صد نی !');
INSERT INTO proverbs(text) VALUES ('آب که سر بالا میره، قورباغه ابوعطا میخونه !');
INSERT INTO proverbs(text) VALUES ('آب نمی بینه و گرنه شناگر قابلیه !');
INSERT INTO proverbs(text) VALUES ('آبی از او گرم نمیشه !');
INSERT INTO proverbs(text) VALUES ('آتش که گرفت، خشک و تر میسوزد !');
INSERT INTO proverbs(text) VALUES ('آخر شاه منشی، کاه کشی است !');
INSERT INTO proverbs(text) VALUES ('آدم با کسی که علی گفت، عمر نمیگه !');
INSERT INTO proverbs(text) VALUES ('آدم بد حساب، دوبار میده !');
INSERT INTO proverbs(text) VALUES ('آدم تنبل، عقل چهل وزیر داره !');
INSERT INTO proverbs(text) VALUES ('آدم خوش معامله، شریک مال مردمه !');
INSERT INTO proverbs(text) VALUES ('آدم دست پاچه، کار را دوبار میکنه !');
INSERT INTO proverbs(text) VALUES ('آدم زنده، زندگی میخواد !');
INSERT INTO proverbs(text) VALUES ('آدم گدا، اینهمه ادا ؟!');
INSERT INTO proverbs(text) VALUES ('آدم گرسنه، خواب نان سنگک می بینه !');
INSERT INTO proverbs(text) VALUES ('آدم ناشی، سرنا را از سر گشادش میزنه !');
INSERT INTO proverbs(text) VALUES ('آرد خودمونو بیختیم، الک مونو آویختیم !');
INSERT INTO proverbs(text) VALUES ('آرزو بر جوانان عیب نیست !');
INSERT INTO proverbs(text) VALUES ('آستین نو پلو بخور !');
INSERT INTO proverbs(text) VALUES ('آسوده کسی که خر نداره — از کاه و جوش خبر نداره !');
INSERT INTO proverbs(text) VALUES ('آسه برو آسه بیا که گربه شاخت نزنه !');
INSERT INTO proverbs(text) VALUES ('آشپز که دوتا شد، آش یا شوره یا بی نمک !');
INSERT INTO proverbs(text) VALUES ('آش نخورده و دهن سوخته !');
INSERT INTO proverbs(text) VALUES ('آفتابه خرج لحیمه !');
INSERT INTO proverbs(text) VALUES ('آفتابه لگن هفت دست، شام و ناهار هیچی !');
INSERT INTO proverbs(text) VALUES ('آفتابه و لولهنگ هر دو یک کار میکنند، اما قیمت شان موقع گرو گذاشتن معلوم میشه !');
INSERT INTO proverbs(text) VALUES ('آمدم ثواب کنم، کباب شدم !');
INSERT INTO proverbs(text) VALUES ('آمد زیر ابروشو برداره، چشمش را کور کرد !');
INSERT INTO proverbs(text) VALUES ('آنچه دلم خواست نه آن شد — آنچه خدا خواست همان شد');
INSERT INTO proverbs(text) VALUES ('آنرا که حساب پاکه، از محاسبه چه باکه ؟!');
INSERT INTO proverbs(text) VALUES ('آنقدر بایست، تا علف زیر پات سبز بشه !');
INSERT INTO proverbs(text) VALUES ('آنقدر سمن هست، که یاسمن توش گمه !');
INSERT INTO proverbs(text) VALUES ('آنقدر مار خورده تا افعی شده !');
INSERT INTO proverbs(text) VALUES ('آن ممه را لولو برد !');
INSERT INTO proverbs(text) VALUES ('آواز دهل شنیده از دور خوشه !');
INSERT INTO proverbs(text) VALUES ('اجاره نشین خوش نشینه !');
INSERT INTO proverbs(text) VALUES ('ارزان خری، انبان خری !');
INSERT INTO proverbs(text) VALUES ('از اسب افتاده ایم، اما از نسل نیفتاده ایم !');
INSERT INTO proverbs(text) VALUES ('از اونجا مونده، از اینجا رونده !');
INSERT INTO proverbs(text) VALUES ('از اون نترس که های و هوی داره، از اون بترس که سر به تو داره !');
INSERT INTO proverbs(text) VALUES ('از این امامزاده کسی معجز نمی بینه !');
INSERT INTO proverbs(text) VALUES ('از این دم بریده هر چی بگی بر میاد !');
INSERT INTO proverbs(text) VALUES ('از این ستون بآن ستون فرجه !');
INSERT INTO proverbs(text) VALUES ('از بی کفنی زنده ایم !');
INSERT INTO proverbs(text) VALUES ('از دست پس میزنه، با پا پیش میکشه !');
INSERT INTO proverbs(text) VALUES ('از تنگی چشم پیل معلومم شد — آنانکه غنی ترند محتاج ترند !');
INSERT INTO proverbs(text) VALUES ('از تو حرکت، از خدا برکت');
INSERT INTO proverbs(text) VALUES ('از حق تا نا حق چهار انگشت فاصله است !');
INSERT INTO proverbs(text) VALUES ('از خر افتاده، خرما پیدا کرده !');
INSERT INTO proverbs(text) VALUES ('از خرس موئی، غنیمته !');
INSERT INTO proverbs(text) VALUES ('از خر میپرسی چهارشنبه کیه ؟!');
INSERT INTO proverbs(text) VALUES ('آنوقت که جیک جیک مستانت بود، یاد زمستانت نبود ؟');
INSERT INTO proverbs(text) VALUES ('آب از آب تکان نخوردن');
INSERT INTO proverbs(text) VALUES ('آب از آسياب افتادن');
INSERT INTO proverbs(text) VALUES ('آب از سر گذشتن');
INSERT INTO proverbs(text) VALUES ('آب آمد و تيمم باطل شد');
INSERT INTO proverbs(text) VALUES ('آب توي دلش تکان نمي خورد');
INSERT INTO proverbs(text) VALUES ('آب خوش از گلو پايين نرفتن');
INSERT INTO proverbs(text) VALUES ('آب در کوزه و ماتشنه لبان مي گرديم');
INSERT INTO proverbs(text) VALUES ('آب را از سرچشمه بايد بست');
INSERT INTO proverbs(text) VALUES ('آب زير پوستش رفته است');
INSERT INTO proverbs(text) VALUES ('آبشان در يک جوي نمي رود');
INSERT INTO proverbs(text) VALUES ('آب غوره گرفتن');
INSERT INTO proverbs(text) VALUES ('آب کش به کف گير مي گويد چقدر سوراخ داري');
INSERT INTO proverbs(text) VALUES ('آبم است وگاوم است نوبت آسيابم است');
INSERT INTO proverbs(text) VALUES ('آب نخوردن چشم');
INSERT INTO proverbs(text) VALUES ('آب تاب دادن');
INSERT INTO proverbs(text) VALUES ('آب در دست داري نخور بيا');
INSERT INTO proverbs(text) VALUES ('آبي از او گم نمي شود');
INSERT INTO proverbs(text) VALUES ('آبي که به زندگيش نديد حسين                         چون گشت شهيد بر مزارش دادند');
INSERT INTO proverbs(text) VALUES ('توجهي  به کسي در زمان لزوم نکردن در غير زمان به آن پرداختن_مانند (نوشداروي پس از مرگ سهراب)');
INSERT INTO proverbs(text) VALUES ('آتش چون بر افروخت بسوزد تر وخشک');
INSERT INTO proverbs(text) VALUES ('آتش زير خاکستر');
INSERT INTO proverbs(text) VALUES ('آخر کار خود را کردن');
INSERT INTO proverbs(text) VALUES ('آخوند شدن چه آسان وانسان شدن چه مشکل');
INSERT INTO proverbs(text) VALUES ('آدم بايد لقمه را به اندازه دهانش بگيرد');
INSERT INTO proverbs(text) VALUES ('آدم شاخ در مي آورد');
INSERT INTO proverbs(text) VALUES ('آدم گدا اين همه ادا');
INSERT INTO proverbs(text) VALUES ('آدم گرسنه سنگ را هم مي خورد');
INSERT INTO proverbs(text) VALUES ('آدم مفتخور خوش سليقه مي شود');
INSERT INTO proverbs(text) VALUES ('آدم ناشي سرنا را از سر گشاد آن مي زند');
INSERT INTO proverbs(text) VALUES ('آدم يکبار پايش تو چاله مي افتد');
INSERT INTO proverbs(text) VALUES ('آدم يک دنده');
INSERT INTO proverbs(text) VALUES ('آرزو را به گور بردن');
INSERT INTO proverbs(text) VALUES ('آزموده را آزمون خطاست');
INSERT INTO proverbs(text) VALUES ('آسمان به زمين نمي آيد');
INSERT INTO proverbs(text) VALUES ('آسمان وريسمان را سر هم بافتن');
INSERT INTO proverbs(text) VALUES ('آش پز که دوتا شد آش يا شور مي شود يا بي نمک');
INSERT INTO proverbs(text) VALUES ('آش دهن سوز نبودن');
INSERT INTO proverbs(text) VALUES ('آش خوب باشد کاسه اش چوب باشد');
INSERT INTO proverbs(text) VALUES ('آش کشک خالته بخوري پاته نخوري پاته');
INSERT INTO proverbs(text) VALUES ('آش نخورده ودهن سوخته');
INSERT INTO proverbs(text) VALUES ('آش و لاش کردن');
INSERT INTO proverbs(text) VALUES ('آشي براي کسي پختن');
INSERT INTO proverbs(text) VALUES ('آفتاب لب بام است');
INSERT INTO proverbs(text) VALUES ('آفتابه لگن هفت دست وشام و ناهار هيچ');
INSERT INTO proverbs(text) VALUES ('آفتاب هميشه زير ابر نمي ماند');
INSERT INTO proverbs(text) VALUES ('آمد زير ابرويش را بگيرد چشمش را کور کرد');
INSERT INTO proverbs(text) VALUES ('آن را که حساب پاک است از معامله چه باک است');
INSERT INTO proverbs(text) VALUES ('آن قدر بايست که زير پايت سبز شود');
INSERT INTO proverbs(text) VALUES ('آن وقت که جيک جيک مستانت بود ياد زمستانت نبود');
INSERT INTO proverbs(text) VALUES ('آويزه گوش کردن');
INSERT INTO proverbs(text) VALUES ('آه در بساط نداشتن');
INSERT INTO proverbs(text) VALUES ('آهسته بيا آهسته برو گربه شاخت نزند');
INSERT INTO proverbs(text) VALUES ('اجاق پدر راروشن نگه داشتن');
INSERT INTO proverbs(text) VALUES ('اجاقش کور است');
INSERT INTO proverbs(text) VALUES ('اجل دور سرش مي چرخد');
INSERT INTO proverbs(text) VALUES ('احترام امام زاد ه با متولي آن است');
INSERT INTO proverbs(text) VALUES ('از آب گل آلود ماهي گرفتن');
INSERT INTO proverbs(text) VALUES ('از اين ستون به آن ستون فرج است');
INSERT INTO proverbs(text) VALUES ('از بيخ عرب بودن');
INSERT INTO proverbs(text) VALUES ('از خر شيطان پياده شدن');
INSERT INTO proverbs(text) VALUES ('از دماغ فيل افتادن');
INSERT INTO proverbs(text) VALUES ('از سه چيز بايد حذر کرد');
INSERT INTO proverbs(text) VALUES ('ا ز کاه کوه ساختن');
INSERT INTO proverbs(text) VALUES ('از کيسه خليفه بخشيدن');
INSERT INTO proverbs(text) VALUES ('از هول حليم توي ديگ افتادن');
INSERT INTO proverbs(text) VALUES ('اسب راگم کردن وپي نعلش گشتن');
INSERT INTO proverbs(text) VALUES ('اگر در ديزي باز است حياي گربه کجا رفته است');
INSERT INTO proverbs(text) VALUES ('اگر دنيا را آب ببرد فلاني را خواب ببرد');
INSERT INTO proverbs(text) VALUES ('اگر کاردش بزني خونش بيرون نمي آيد');
INSERT INTO proverbs(text) VALUES ('اگر کاه از تو نيست کاهدان از تو است');
INSERT INTO proverbs(text) VALUES ('انگشت در سوراخ زنبور کردن');
INSERT INTO proverbs(text) VALUES ('ايراد بني اسرائيلي گرفتن');
INSERT INTO proverbs(text) VALUES ('اين شتري است که در خانه هرکس مي خوابد');
INSERT INTO proverbs(text) VALUES ('اين کلاه براي سرش گشاد است');
INSERT INTO proverbs(text) VALUES ('با پاي بروي کفش پاره مي شود وباسر بروي کلاه');
INSERT INTO proverbs(text) VALUES ('با پنبه سر بريدن');
INSERT INTO proverbs(text) VALUES ('باد آورده را باد مي برد');
INSERT INTO proverbs(text) VALUES ('باد غبغب انداختن');
INSERT INTO proverbs(text) VALUES ('باد در فقس کردن');
INSERT INTO proverbs(text) VALUES ('بامجان بم آفت ندارد');
INSERT INTO proverbs(text) VALUES ('باسيلي صورت خود را سرخ داشتن');
INSERT INTO proverbs(text) VALUES ('با کدخدا بساز ؛ده را بتاز');
INSERT INTO proverbs(text) VALUES ('بالاخانه اش را اجاره داده است');
INSERT INTO proverbs(text) VALUES ('بالاي سياهي رنگي نيست');
INSERT INTO proverbs(text) VALUES ('با يک تير دونشانه زدن');
INSERT INTO proverbs(text) VALUES ('با يک دست دهندوانه نمي توان گرفت');
INSERT INTO proverbs(text) VALUES ('بچه عزيز است و ادب  عزيز تر');
INSERT INTO proverbs(text) VALUES ('بزک نمير بهار مي آيد کمبزه با خيار مي آيد');
INSERT INTO proverbs(text) VALUES ('برادري به جا بز غاله يکي هفت صد دينار');
INSERT INTO proverbs(text) VALUES ('براي يک بي نماز در مسجد را نمي بندند');
INSERT INTO proverbs(text) VALUES ('برج زهر مار بودن');
INSERT INTO proverbs(text) VALUES ('بر خر مراد خود سوار شدن');
INSERT INTO proverbs(text) VALUES ('برو کشکت را بساب');
INSERT INTO proverbs(text) VALUES ('بز گر از سرچشمه آب مي خورد');
INSERT INTO proverbs(text) VALUES ('بلد نيستم راحت جان است');
INSERT INTO proverbs(text) VALUES ('به بوي کباب آمديم ديدم خر داغ مي کنند');
INSERT INTO proverbs(text) VALUES ('به تنبل گفتند برو سايه گفت سايه خودش مي آيد');
INSERT INTO proverbs(text) VALUES ('به جيب زدن');
INSERT INTO proverbs(text) VALUES ('به چاک زدن');
INSERT INTO proverbs(text) VALUES ('به در د لاي جرز خوردن');
INSERT INTO proverbs(text) VALUES ('به دريابرود دريا خشک مي شود');
INSERT INTO proverbs(text) VALUES ('به رنج و سعي کسي نعمتي به چنک آورد         دگر کس آيدو بي سعي و رنج بردارد');
INSERT INTO proverbs(text) VALUES ('توجه به مفت خوري افراد دارد');
INSERT INTO proverbs(text) VALUES ('به روباه گفتند شاهدت کيست گفت دمم');
INSERT INTO proverbs(text) VALUES ('يه رش کسي خنديدن');
INSERT INTO proverbs(text) VALUES ('به زخم کسي نمک پاشيدن');
INSERT INTO proverbs(text) VALUES ('به شتر گفتند چرا گردنت کج است گفت کجايم راست است');
INSERT INTO proverbs(text) VALUES ('به شترمرغ گفتند بپرگفت شترم گفتند بار ببر گفت مرغم');
INSERT INTO proverbs(text) VALUES ('به شکم خود صابون زدن');
INSERT INTO proverbs(text) VALUES ('به کچل گفتند نامت چيست گفت');
INSERT INTO proverbs(text) VALUES ('به گمراه گفتند نامت چيست گفت');
INSERT INTO proverbs(text) VALUES ('به هر سازي رقصيدن');
INSERT INTO proverbs(text) VALUES ('بي بي از بي چادري پنهان است');
INSERT INTO proverbs(text) VALUES ('بي گدار به آب زدن');
INSERT INTO proverbs(text) VALUES ('پا از گليم بيرو ن بردن');
INSERT INTO proverbs(text) VALUES ('پايش لب گور است');
INSERT INTO proverbs(text) VALUES ('پدر کسي را سوزاندن');
INSERT INTO proverbs(text) VALUES ('پدر کشي داشتن باکسي');
INSERT INTO proverbs(text) VALUES ('پدر مادر دار بودن');
INSERT INTO proverbs(text) VALUES ('پرت پلا گفتن');
INSERT INTO proverbs(text) VALUES ('پرسه زدن');
INSERT INTO proverbs(text) VALUES ('پُز عالي وجيب خالي');
INSERT INTO proverbs(text) VALUES ('پس از مرگ سهراب ونوشدارو');
INSERT INTO proverbs(text) VALUES ('پستان به تنور چسباندن');
INSERT INTO proverbs(text) VALUES ('پشت سر کسي نماز خواندن');
INSERT INTO proverbs(text) VALUES ('پشت کسي را به خاک ماليدن');
INSERT INTO proverbs(text) VALUES ('پيله کردن');
INSERT INTO proverbs(text) VALUES ('تابستان پدر يتيمان است');
INSERT INTO proverbs(text) VALUES ('تا پول داري رفيقتم عاشق بند کيفتم');
INSERT INTO proverbs(text) VALUES ('تا تنور گرم است بايد نان را چسباند');
INSERT INTO proverbs(text) VALUES ('تابگويي((ف))مي گويم فرح زاد');
INSERT INTO proverbs(text) VALUES ('تا سه نشود بازي نشود');
INSERT INTO proverbs(text) VALUES ('تا گوساله گاو شو دل صاحب آب شود');
INSERT INTO proverbs(text) VALUES ('تا نباشد ،چوب تر فرمان نبرد گاو خر');
INSERT INTO proverbs(text) VALUES ('تا نباشد چيزکي مردم نگويند چيز ها');
INSERT INTO proverbs(text) VALUES ('تخم مرغ دزد شتر مرغ دزد مي شود');
INSERT INTO proverbs(text) VALUES ('تر وخشک را باهم سوختن');
INSERT INTO proverbs(text) VALUES ('تعارف شاه عبدالعظيمي کردن');
INSERT INTO proverbs(text) VALUES ('توبه ي گرگ مر گ است');
INSERT INTO proverbs(text) VALUES ('تو به خير و من به سلامت');
INSERT INTO proverbs(text) VALUES ('تو نيکي مي کن و در دجله  انداز که ايزد در بيابانت دهد باز');
INSERT INTO proverbs(text) VALUES ('توي هچل افتادن');
INSERT INTO proverbs(text) VALUES ('توي هول و ولا ماندن');
INSERT INTO proverbs(text) VALUES ('ته جيبش تار عنکبوت بسته است');
INSERT INTO proverbs(text) VALUES ('جايي نمي رود که آبرويش رود');
INSERT INTO proverbs(text) VALUES ('جان به عزرائيل ندادن');
INSERT INTO proverbs(text) VALUES ('جاي سوزن انداختن نبود');
INSERT INTO proverbs(text) VALUES ('چرت موز بودن');
INSERT INTO proverbs(text) VALUES ('جلز ولز کردن');
INSERT INTO proverbs(text) VALUES ('جنسش شيشه خورده دارد');
INSERT INTO proverbs(text) VALUES ('جواب ابلهان خاموشي است');
INSERT INTO proverbs(text) VALUES ('جوجه را در آخر پاييز مي شمرند');
INSERT INTO proverbs(text) VALUES ('آمد  جور استاد به زمهر پدر');
INSERT INTO proverbs(text) VALUES ('جيم شدن');
INSERT INTO proverbs(text) VALUES ('چا خان کردن');
INSERT INTO proverbs(text) VALUES ('چاقو دسته ي خود را نمي برد');
INSERT INTO proverbs(text) VALUES ('چاق سلامتي کردن');
INSERT INTO proverbs(text) VALUES ('چپ چپ نگاه کردن');
INSERT INTO proverbs(text) VALUES ('چراغي که به خانه رواست به مسجد حرام است');
INSERT INTO proverbs(text) VALUES ('چشمش شور است');
INSERT INTO proverbs(text) VALUES ('چاه کن هميشه ته چاه است');
INSERT INTO proverbs(text) VALUES ('چوب تر به کسي فروختن');
INSERT INTO proverbs(text) VALUES ('چوب دوسر نجس');
INSERT INTO proverbs(text) VALUES ('چوب لاي چرخ گذاشتن');
INSERT INTO proverbs(text) VALUES ('چو دخلت نيست خرج آهسته تر کن');
INSERT INTO proverbs(text) VALUES ('چانه اش گرم شد');
INSERT INTO proverbs(text) VALUES ('چه خاکي به سرم بريزم');
INSERT INTO proverbs(text) VALUES ('چيزي در چنته نداشتن');
INSERT INTO proverbs(text) VALUES ('حرف راست را از دهن بچه بايد شنيد');
INSERT INTO proverbs(text) VALUES ('حساب به دينار، بخشش به خروار');
INSERT INTO proverbs(text) VALUES ('حق کسي را کف دستش گذاشتن');
INSERT INTO proverbs(text) VALUES ('حلواي تنتناني تا نخوري نداني');
INSERT INTO proverbs(text) VALUES ('حمام زنانه شدن');
INSERT INTO proverbs(text) VALUES ('حلزون خود را به جمع شاخدارها مي کند');
INSERT INTO proverbs(text) VALUES ('حنايش رنگ ندارد');
INSERT INTO proverbs(text) VALUES ('خاله زنک بازي در آوردن');
INSERT INTO proverbs(text) VALUES ('خدا نجار نيست اما درو تخته را خوب به هم مي اندازد');
INSERT INTO proverbs(text) VALUES ('(به ويژه زن و مرد )');
INSERT INTO proverbs(text) VALUES ('خر بيارو باقالا بار کن');
INSERT INTO proverbs(text) VALUES ('خر پول');
INSERT INTO proverbs(text) VALUES ('خر تو خر بودن');
INSERT INTO proverbs(text) VALUES ('خر خالي يرقه مي رود');
INSERT INTO proverbs(text) VALUES ('خر را که به عروسي مي برند براي خوشي نيست براي آبکشي است');
INSERT INTO proverbs(text) VALUES ('خر رفت و الاغ برگشت');
INSERT INTO proverbs(text) VALUES ('خرس را به رقص آورديم دمش را به دست آورديم');
INSERT INTO proverbs(text) VALUES ('خر کوزه پر از شنبه تا پنج شنبه گچ آوردن وجمعه سنگ کشيدن');
INSERT INTO proverbs(text) VALUES ('خر مقدس بودن');
INSERT INTO proverbs(text) VALUES ('خروس بي محل بودن');
INSERT INTO proverbs(text) VALUES ('خر همان خر است اما پالانش عوض شده');
INSERT INTO proverbs(text) VALUES ('خر هميشه خرما نمي ريند');
INSERT INTO proverbs(text) VALUES ('خل بازي در آوردن');
INSERT INTO proverbs(text) VALUES ('خواب زن چپ است');
INSERT INTO proverbs(text) VALUES ('خواهي نشوي رسوا همرنگ جماعت شو');
INSERT INTO proverbs(text) VALUES ('خود را به کوچه ي علي چپ زدن');
INSERT INTO proverbs(text) VALUES ('خود را نخود آشي کردن');
INSERT INTO proverbs(text) VALUES ('خودش مي برد وخودش مي دوزد');
INSERT INTO proverbs(text) VALUES ('خون کسي را توي شيشه کردن');
INSERT INTO proverbs(text) VALUES ('داشتم داشتم صاحب نيست دارم دارم صاحب است');
INSERT INTO proverbs(text) VALUES ('داغ شکم از داغ عزيزان کمتر نيست');
INSERT INTO proverbs(text) VALUES ('دانا هم داند وهم پرسد ،نادان نداند ونپرسد');
INSERT INTO proverbs(text) VALUES ('دبه در آوردن');
INSERT INTO proverbs(text) VALUES ('دختر تر تيزک است');
INSERT INTO proverbs(text) VALUES ('در جنگ نان وحلوا تقسيم نمي کنند');
INSERT INTO proverbs(text) VALUES ('در خانه هر چه مهمان هر که');
INSERT INTO proverbs(text) VALUES ('درخت گردو به اين بزرگي درخت خربزه الله اکبر');
INSERT INTO proverbs(text) VALUES ('درد خروار آيد و مثقال رود');
INSERT INTO proverbs(text) VALUES ('درد را کي ميکشد که مي زايد');
INSERT INTO proverbs(text) VALUES ('در حوضي که ماهي نيست قورباغه سپهسالار است');
INSERT INTO proverbs(text) VALUES ('در ديزي باز است حياي گربه کجا رفت');
INSERT INTO proverbs(text) VALUES ('در مثل مناقشه نيست');
INSERT INTO proverbs(text) VALUES ('دزد آمد و هيچ نبرد');
INSERT INTO proverbs(text) VALUES ('دزد نگرفته پادشاه است');
INSERT INTO proverbs(text) VALUES ('دست از سر کچل کسي برادشتن');
INSERT INTO proverbs(text) VALUES ('دست به سر کردن');
INSERT INTO proverbs(text) VALUES ('دست به دهان رسيدن');
INSERT INTO proverbs(text) VALUES ('دست به يقه شدن');
INSERT INTO proverbs(text) VALUES ('دست راست و چپ را نشناختن');
INSERT INTO proverbs(text) VALUES ('دست دست را مي شناسد');
INSERT INTO proverbs(text) VALUES ('دستش چسبناک است');
INSERT INTO proverbs(text) VALUES ('دستش نمک ندارد');
INSERT INTO proverbs(text) VALUES ('دست و پاي خود را گم کردن');
INSERT INTO proverbs(text) VALUES ('دست و پنجه نرم کردن');
INSERT INTO proverbs(text) VALUES ('روده بزرگ روده گوچک را خورده است');
INSERT INTO proverbs(text) VALUES ('روزه ي کله گنجشکي گرفتن');
INSERT INTO proverbs(text) VALUES ('دل به دل راه داشتن');
INSERT INTO proverbs(text) VALUES ('دلش مثل سير و سرکه مي جوشد');
INSERT INTO proverbs(text) VALUES ('دماغي چاق داشتن');
INSERT INTO proverbs(text) VALUES ('دماغ کسي را به خاک ماليدن');
INSERT INTO proverbs(text) VALUES ('دم به تله دادن');
INSERT INTO proverbs(text) VALUES ('دم بخت بودن');
INSERT INTO proverbs(text) VALUES ('دم در آوردن');
INSERT INTO proverbs(text) VALUES ('دمش را گذاشت روي کولش و رفت');
INSERT INTO proverbs(text) VALUES ('دندان را تيز');
INSERT INTO proverbs(text) VALUES ('دهن بين بودن');
INSERT INTO proverbs(text) VALUES ('دهنش چفت و بست ندارد');
INSERT INTO proverbs(text) VALUES ('ديوار موش دارد موش گوش دارد');
INSERT INTO proverbs(text) VALUES ('ذکر خير کسي را کردن');
INSERT INTO proverbs(text) VALUES ('رو دست خوردن');
INSERT INTO proverbs(text) VALUES ('روزگار کسي را سياه کردن');
INSERT INTO proverbs(text) VALUES ('روز وانفسا');
INSERT INTO proverbs(text) VALUES ('روزه ي بي نمازي');
INSERT INTO proverbs(text) VALUES ('روزه خوردنش را ديده ايم نماز کردنش را نديده ايم');
INSERT INTO proverbs(text) VALUES ('روي سر کسي خراب شدن');
INSERT INTO proverbs(text) VALUES ('روي شاخش است');
INSERT INTO proverbs(text) VALUES ('روي کسي را سفيد کردن');
INSERT INTO proverbs(text) VALUES ('ريش خود را به دست ديگري دادن');
INSERT INTO proverbs(text) VALUES ('ريش خود را در آسياب سفيد کرده');
INSERT INTO proverbs(text) VALUES ('ريش و قيچي هر دو را به دست داشتن');
INSERT INTO proverbs(text) VALUES ('ريگي در کفش داشتن');
INSERT INTO proverbs(text) VALUES ('زمين دهان باز کرد و مرا در خود فرو برد');
INSERT INTO proverbs(text) VALUES ('زن از غازه سرخ شود مرد از غزا');
INSERT INTO proverbs(text) VALUES ('زن نانجيب گرفتن آسان و نگه داشتن او مشکل');
INSERT INTO proverbs(text) VALUES ('زن نانجيب گرفتن مشکل و نگه داشتن او آسان');
INSERT INTO proverbs(text) VALUES ('زير اندازش زمين است و رو اندازش آسمان');
INSERT INTO proverbs(text) VALUES ('زيرآب کسي را زدن');
INSERT INTO proverbs(text) VALUES ('زير کاسه اي نيم کاسه اي بودن');
INSERT INTO proverbs(text) VALUES ('زيره به کرمان بردن');
INSERT INTO proverbs(text) VALUES ('زينب ستم کش است');
INSERT INTO proverbs(text) VALUES ('سال به سال دريغ از پارسال');
INSERT INTO proverbs(text) VALUES ('سالي که نکوست از بهارش پيداست');
INSERT INTO proverbs(text) VALUES ('سبيل کسي را چرب کردن');
INSERT INTO proverbs(text) VALUES ('سبيل کسي را دود دادن');
INSERT INTO proverbs(text) VALUES ('ستاره ي سهيل است');
INSERT INTO proverbs(text) VALUES ('سر به جهنم زدن');
INSERT INTO proverbs(text) VALUES ('سر به سر کسي گذاشتن');
INSERT INTO proverbs(text) VALUES ('سر به صحرا زدن');
INSERT INTO proverbs(text) VALUES ('سر به هوا بودن');
INSERT INTO proverbs(text) VALUES ('سر پل خر بگيري');
INSERT INTO proverbs(text) VALUES ('سر پيري و معرکه گيري');
INSERT INTO proverbs(text) VALUES ('سرد وگرم روزگار و چشيدن');
INSERT INTO proverbs(text) VALUES ('سر شاخ شدن');
INSERT INTO proverbs(text) VALUES ('سرش تو لاک خود بودن');
INSERT INTO proverbs(text) VALUES ('سر کسي را گرم کردن');
INSERT INTO proverbs(text) VALUES ('سر کسي شيره ماليدن');
INSERT INTO proverbs(text) VALUES ('سرکه ي مفت شيرين تر از عسل است');
INSERT INTO proverbs(text) VALUES ('سر کيسه را شل کردن');
INSERT INTO proverbs(text) VALUES ('سرم را بشکن و نرخم را نشکن');
INSERT INTO proverbs(text) VALUES ('سر و گوش آب دادن');
INSERT INTO proverbs(text) VALUES ('سري که درد نمي کند دستمال نبند');
INSERT INTO proverbs(text) VALUES ('سگ صاحبش را نمي شناسد');
INSERT INTO proverbs(text) VALUES ('سگ کيش کردن');
INSERT INTO proverbs(text) VALUES ('سير تا پياز را براي کسي نقل کردن');
INSERT INTO proverbs(text) VALUES ('سير به پياز مي گه که پيف پيف چقدر بو ميدهي');
INSERT INTO proverbs(text) VALUES ('شاخ و شانه کشيدن');
INSERT INTO proverbs(text) VALUES ('شال و کلاه کردن');
INSERT INTO proverbs(text) VALUES ('شب آبستن است تا چه زايد سحر');
INSERT INTO proverbs(text) VALUES ('شب دراز است و قلندر بيدار');
INSERT INTO proverbs(text) VALUES ('شتر با بارش گم شد');
INSERT INTO proverbs(text) VALUES ('شتر ديدي نديدي');
INSERT INTO proverbs(text) VALUES ('شتر سواري دولا دولا نداره');
INSERT INTO proverbs(text) VALUES ('شريک دزد و رفيق قافله');
INSERT INTO proverbs(text) VALUES ('شش ماهه به دنيا آمدن');
INSERT INTO proverbs(text) VALUES ('شکم گرسنه فتواي خون مي دهد');
INSERT INTO proverbs(text) VALUES ('شيري يا روباه؟');
INSERT INTO proverbs(text) VALUES ('شورش را در آوردن');
INSERT INTO proverbs(text) VALUES ('شتر در خواب بيند پنبه دانه');
INSERT INTO proverbs(text) VALUES ('شيطان را درس دادن');
INSERT INTO proverbs(text) VALUES ('صبر ايوب داشتن');
INSERT INTO proverbs(text) VALUES ('صد سال گدايي کرد امّا شب جمعه را نميداند');
INSERT INTO proverbs(text) VALUES ('صلاح مملکت خويش خسروان دانند');
INSERT INTO proverbs(text) VALUES ('طناب مفت را کرديد خود را به دار زد');
INSERT INTO proverbs(text) VALUES ('طوطي وار ياد گرفتن');
INSERT INTO proverbs(text) VALUES ('عاقبت جوينده يابنده بود');
INSERT INTO proverbs(text) VALUES ('عقل کسي گرد شدن');
INSERT INTO proverbs(text) VALUES ('علي ماند و حوضش');
INSERT INTO proverbs(text) VALUES ('عمر نوح نداشتن');
INSERT INTO proverbs(text) VALUES ('عيسي به دين خود موسي هم به دين خود');
INSERT INTO proverbs(text) VALUES ('غاز چراندن');
INSERT INTO proverbs(text) VALUES ('غزل خدا حافظي را خواندن');
INSERT INTO proverbs(text) VALUES ('فرار وبر قرار ترجيع دادن');
INSERT INTO proverbs(text) VALUES ('فس فس کردن');
INSERT INTO proverbs(text) VALUES ('فضول و بردن جهنم گفت هيزمش تر است');
INSERT INTO proverbs(text) VALUES ('فلفل مبين که ريزه / بشکن ببين چه تيزاست');
INSERT INTO proverbs(text) VALUES ('فيلش ياد هندوستان کرده');
INSERT INTO proverbs(text) VALUES ('قارت وقورت کردن');
INSERT INTO proverbs(text) VALUES ('قلق کسي را به دست آوردن');
INSERT INTO proverbs(text) VALUES ('قوز بالاي قوز');
INSERT INTO proverbs(text) VALUES ('کاچي بهتر از هيچي است');
INSERT INTO proverbs(text) VALUES ('کاردش بزني خونش در نمي آيد');
INSERT INTO proverbs(text) VALUES ('کاري بکن بهر ثواب نه سيخ بسوزد نه کباب');
INSERT INTO proverbs(text) VALUES ('کبکش خروس مي خواند');
INSERT INTO proverbs(text) VALUES ('کس نخوارد پشت من جز ناخن انگشت من');
INSERT INTO proverbs(text) VALUES ('کار حضرت فيل است');
INSERT INTO proverbs(text) VALUES ('کف دستم را بو نکرده بودم');
INSERT INTO proverbs(text) VALUES ('کل اگر طبيب بودي سر خود دوا نمودي');
INSERT INTO proverbs(text) VALUES ('کلاه شرعي بافتن');
INSERT INTO proverbs(text) VALUES ('کار کردن خر وخوردن يابو');
INSERT INTO proverbs(text) VALUES ('کيسه براي چيزي دوختن');
INSERT INTO proverbs(text) VALUES ('گاوش زائيده');
INSERT INTO proverbs(text) VALUES ('گردن کج کردن');
INSERT INTO proverbs(text) VALUES ('گر صبر کني ز غوره حلوا سازي');
INSERT INTO proverbs(text) VALUES ('گز نکرده پاره کردن');
INSERT INTO proverbs(text) VALUES ('گل سر سبد بودن');
INSERT INTO proverbs(text) VALUES ('گاو پيشاني سفيد');
INSERT INTO proverbs(text) VALUES ('گوش بريدن کسي');
INSERT INTO proverbs(text) VALUES ('لفت دادن کاري');
INSERT INTO proverbs(text) VALUES ('لنگه کفش کهنه در بيابان نعمت است');
INSERT INTO proverbs(text) VALUES ('مار پوست خود بگذارد اما خوي خود نگذارد');
INSERT INTO proverbs(text) VALUES ('مار را در آستين خود پروراندن');
INSERT INTO proverbs(text) VALUES ('مار گزيده از ريسمان سياه وسفيد مي ترسد');
INSERT INTO proverbs(text) VALUES ('ماست خود را کيسه کردن');
INSERT INTO proverbs(text) VALUES ('مثل اينکه مال باباش و خوردم');
INSERT INTO proverbs(text) VALUES ('ماهي را هر وقت از آب بگيري تازه است');
INSERT INTO proverbs(text) VALUES ('مرغ همسايه غاز است');
INSERT INTO proverbs(text) VALUES ('موش به سوراخ نمي رفت جارو به دمبش بست');
INSERT INTO proverbs(text) VALUES ('مرغ يک پا دارد');
INSERT INTO proverbs(text) VALUES ('مثل خر در گل ماندن');
INSERT INTO proverbs(text) VALUES ('مرد سر مي دهد اما سر نمي دهد');
INSERT INTO proverbs(text) VALUES ('مشت نمونه خروار است');
INSERT INTO proverbs(text) VALUES ('مشت وسندان');
INSERT INTO proverbs(text) VALUES ('مگر آمدي آتش ببري');
INSERT INTO proverbs(text) VALUES ('مگر  شهر هرت است ؟ هر کار ي انجام بدهي آزاد نيستي');
INSERT INTO proverbs(text) VALUES ('مگر کله گنجشک خورده اي ؟ بسيار پر حرف هستي');
INSERT INTO proverbs(text) VALUES ('من مي گويم نر است تو مي گويي بدوش  - بي جهت اصرار کردن');
INSERT INTO proverbs(text) VALUES ('من يک پيراهن بيشتر از تو پاره کردم- با تجربه تر و سالخورده تر از تو هستم');
INSERT INTO proverbs(text) VALUES ('مو را از دست کشيدن - دقت بسيار کردن');
INSERT INTO proverbs(text) VALUES ('موش مردگي درآوردن خود را به ناخوشي زدن-  خود را بيمار جلوه دادن');
INSERT INTO proverbs(text) VALUES ('مومن مسجد نديده - به شوخي به کسي مي گويند که تظاهر به تقدس دارد');
INSERT INTO proverbs(text) VALUES ('موهايش را در آسياب سفيد کرده  -  گرچه پير است اما بي تجربه است');
INSERT INTO proverbs(text) VALUES ('مويي از خرس کندن غنيمت است  -  از آدم خسيس حداقل استفاده هم غنيمت است');
INSERT INTO proverbs(text) VALUES ('مهمان مهمان را نمي تواند ببيند صاحبخانه هر دو را - خسيس بودن صاحب خانه');
INSERT INTO proverbs(text) VALUES ('ميانشان شکر آب است  - روابط آنها خوب نيست ، اختلاف دارند');
INSERT INTO proverbs(text) VALUES ('ناز شست گرفتن  -  پاداش و جايزه گرفتن');
INSERT INTO proverbs(text) VALUES ('نازک نارنجي  - زودرنج ، کم تحمل در مقابل مشکلات');
INSERT INTO proverbs(text) VALUES ('نان به نرخ روز خوردن  -  پاي بند بودن به اصول - رفتار خود را با وضع حاضر تطبيق دادن');
INSERT INTO proverbs(text) VALUES ('نان کسي را آجر کردن  -موجب ضرر و زيان کسي شدن');
INSERT INTO proverbs(text) VALUES ('نخود هر آش بودن - مداخله در هر کاري کردن');
INSERT INTO proverbs(text) VALUES ('نشخوار آدميزاد حرف است - لذت داشتن حرف زياد');
INSERT INTO proverbs(text) VALUES ('نمک پرورده بودن - مديون کسي ديگر بودن');
INSERT INTO proverbs(text) VALUES ('نو که آمد به بازار    کهنه شود دل آزار - با آمدن چيز جديد گذشته و قديمي و دلگير مي شود');
INSERT INTO proverbs(text) VALUES ('370 – نه زنگي زنگ نه رومي روم- ميانه رو بودن-  متوسط بودن');
INSERT INTO proverbs(text) VALUES ('نه سر پياز نه ته پياز- کاره اي نبودن');
INSERT INTO proverbs(text) VALUES ('نه چک زدم نه چانه عروس آمد به خانه -  بدون زحمت به هدف رسيدم');
INSERT INTO proverbs(text) VALUES ('وقت سر خاراندن نداشتن - سخت گرفتار کار زياد بودن');
INSERT INTO proverbs(text) VALUES ('هر چه بگندد نمکش مي زنند   واي به روزي که بگندد نمک- از افراد درست ديگر انتظار انجام کار بد و زشت نيست');
INSERT INTO proverbs(text) VALUES ('هر چه پول بدهي آش مي خوري - به اندازه زحمتت نتيجه مي گيري');
INSERT INTO proverbs(text) VALUES ('هر سرازي سربالايي دارد- راحتي سختيهايي هم به دنبال دارد');
INSERT INTO proverbs(text) VALUES ('هر چه ديدي از چشم خودت ديدي-  مقصر خودت هستي');
INSERT INTO proverbs(text) VALUES ('378 – هر چه سنگ است مال پاي لنگ است-  آسيب و صدمه هميشه به آدمهاي بيچاره مي رسد');
INSERT INTO proverbs(text) VALUES ('هر کي با آل علي درافتد برافتد - معمولاً سادات به مخالفان خود مي گويند');
INSERT INTO proverbs(text) VALUES ('هر کس به اميد همسايه نشيند گرسنه مي خوابد-  به ديگران نبايد اميد داشت ، هر کاري را بايد خود انجام داد');
INSERT INTO proverbs(text) VALUES ('هر کس خربزه مي خورد پاي لرزش هم مي نشيند- هر کس بايد عاقبت اعمال خود را تحمل کند');
INSERT INTO proverbs(text) VALUES ('هر که بامش بيش برفش بيشتر-  هر کس داراتر است گرفتار تر است');
INSERT INTO proverbs(text) VALUES ('هر که نان از عمل خويش خورد    منت حاتم طايي نبرد -  نبايد به ديگران متکي بود');
INSERT INTO proverbs(text) VALUES ('هر که طاوس خواهد جور هندوستان کشد - بايد سختيها را براي رسيدن به هدف تحمل کرد');
INSERT INTO proverbs(text) VALUES ('هفت خوان رستم را طي کردن- کار بسيار سخت را براي رسيدن به هدف تحمل کرد');
INSERT INTO proverbs(text) VALUES ('همه را برق مي گيرد ما را چراغ نفتي - شانس و اقبال ديگران ييشتر  از ماست');
INSERT INTO proverbs(text) VALUES ('هنداونه زير بغل کسي گذاشتن - تملق بي جا گفتن');
INSERT INTO proverbs(text) VALUES ('هوا گرگ و ميش است-  نه تاريک است نه روشن');
INSERT INTO proverbs(text) VALUES ('هيچ کاره ي همه کاره - آدم هيچ کاره هود را همه کاره مي پندارد');
INSERT INTO proverbs(text) VALUES ('ياسين به گوش خر خواندن - کار بي حاصل انجام دادن');
INSERT INTO proverbs(text) VALUES ('يال و کوپال داشتن - سرو وضع خوب داشتن');
INSERT INTO proverbs(text) VALUES ('يک دستي گرفتن - کسي را کتر از آنچه هست پنداشتن');
INSERT INTO proverbs(text) VALUES ('يک ستاره توي آسمان ندارد -ادم بي شانس و اقبال است');
INSERT INTO proverbs(text) VALUES ('يک شب هزار شب نمي شود -به تعارف به مهمان مي گويند');
INSERT INTO proverbs(text) VALUES ('يک کلاغ چهل کلاغ کردن- اغراق و مبالغه نمودن + غيبت زياد');
INSERT INTO proverbs(text) VALUES ('يک بز گر گله را گرگين مي کند- يک همنشين بد ديگران را هم به فساد مي کشاند');
INSERT INTO proverbs(text) VALUES ('يکي به نعل مي زند يکي هم به ميخ -هر دو طرف را مراعات مي کند');
INSERT INTO proverbs(text) VALUES ('يک گوش در است و گوش ديگر  دروازه  - کسي که مطلبي را به خاطر نمي سپارد');
INSERT INTO proverbs(text) VALUES ('يکي را پي نخود سياه فرستادن - به بهانه اي او را ازميدان خارج کردن');
INSERT INTO proverbs(text) VALUES ('يکي نان نداشت بخورد پياز مي خورد تا اشتهايش باز شود  - کار نابخردانه کردن');
